default: &default
  adapter: postgresql
  host: localhost
  pool: 5

development:
  <<: *default
  database: skywalker_dev

test:
  <<: *default
  database: skywalker_test

production:
  url: <%= ENV['DATABASE_URL'] %>
